### PR TITLE
feat: clear button event emitter added

### PR DESCRIPTION
**Pull request by umernaeem217**
Added an event emitter `clearClicked` which will be emitted when the clear button on the calendar is clicked.

### CODE REVIEW

**Comment by umernaeem217** [comment]
@fetrarij Please check again. I can help you maintain this repository. Any other task?

**Comment by fetrarij** [comment]
@umernaeem217 thanks , that's awesome, you PR will be welcomed

**Comment by fetrarij** [comment]
Hi @umernaeem217 does it fixes the issue https://github.com/fetrarij/ngx-daterangepicker-material/issues/439 ?

**Comment by umernaeem217** [comment]
No @fetrarij no work is done to suppress the events.

**Pull request merged**
