### PR TITLE
Fix ng add

### PR DESCRIPTION
**Pull request by Timebutt**
This PR fixes the `ng add` functionality, allowing users to easily add `ngx-daterangepicker-material` to their project. It also checks for `@angular/material` and `@angular/cdk` (as these are required dependencies) and adds them automatically.

### CODE REVIEW

**Comment by Timebutt** [comment]
@fetrarij as promised: I checked and `ng add` didn't work correctly. Found the correct way to debug it locally and fixed ;)

**Comment by Timebutt** [comment]
Thanks for merging, could you publish `3.0.1` so I can verify it correctly works now?

**Comment by fetrarij** [comment]
@Timebutt v3.0.1 is up, you can verify now, and thanks ;)

**Comment by Timebutt** [comment]
Hey @fetrarij, sorry it took some time but I just tried it out on a new empty Angular project and `ng add` works flawlessly ;)

**Pull request merged**
