### PR TITLE
added showCancel flag in directive and demo

### PR DESCRIPTION
**Pull request by yousefkhan**
Following are the changes. 

1. Added the `showCancel` flag in `DaterangepickerComponent` and `DaterangepickerDirective`.
2. Now the cancel button will not be shown by default. 
3. Updated demo full component to reflect the flag changes.

### CODE REVIEW

**Comment by fetrarij** [comment]
Thanks @yousefkhan , could you set [showCancel]="true"  on the demo in ./demo/src/app/simple/simple.component.html

**Comment by yousefkhan** [comment]
ok

**Comment by yousefkhan** [comment]
Just pushed again and verified the tests too. Let me know if there are still issues

**Comment by fetrarij** [comment]
@yousefkhan done.
Now you can get updated code from master (or master-mat) , then create a new PR for the material : PR to master-mat

**Pull request merged**
