### PR TITLE
Migration/angular10

### PR DESCRIPTION
**Pull request by psaawkel**
Ready to run with Angular 10 (what I've done on my project), i changed:
- tsconfig changes according to Angular recommendation
- .css files changed automatically with Angular Material update
- all libraries updated to latest except ng-packagr becouse of problems in building ("ERROR: Unknown version 80 of android") - last working version is 9.1.1

Trying your version 3.0.2 on Angular 10 project was "ERROR Error: No component factory found for DaterangepickerComponent. Did you add it to @NgModule.entryComponents?" to fix this issue library should be compiled with Angular 10

### CODE REVIEW

**Comment by fetrarij** [comment]
@psaawkel thanks for your input.
I dont think we need to modify something to have it work with angular 10. I tried with 3.0.4 and it works with angular 10.
I needed to clean the repo (remove some css) so your branch is probably out of sync, but before, could you tru 3.0.4 with angular 10?
Did you add .forRoot()?
Thanks

**Comment by fetrarij** [comment]
@psaawkel use v3.0.4, it works with angular 10. I am going to close the PR.

https://github.com/fetrarij/ngx-daterangepicker-material/issues/299

**Comment by altarasyuk** [comment]
As angular 10 uses tslib 2.0.0 this dependency should be changed as well.

`npm WARN ngx-daterangepicker-material@3.0.4 requires a peer of tslib@^1.10.0 but none is installed. You must install peer dependencies yourself.
`

**Comment by fetrarij** [comment]
Since this has conflict with the main branch, I am now closing the PR.
According to the poll https://github.com/fetrarij/ngx-daterangepicker-material/issues/308 I'm going to revive v2 for now.
Thanks

**Pull request closed without merging**
