### PR TITLE
Upgrade to angular 9

### PR DESCRIPTION
**Pull request by Timebutt**
This pull request upgrades the repository to the latest release of **Angular** (`9.1.0`), allowing us to use new features that the framework and most notably the `@angular/cdk` offers.

### CODE REVIEW

**Comment by fetrarij** [comment]
Hello @Timebutt , thanks for your effort.
I have just one question: if it is merged, does the component would work with older version (less than 9) so we can keep with 2.x.X or do we need to upgrade the component to  3.0.0 ?

**Comment by Timebutt** [comment]
Hi @fetrarij, as explained in [this article](https://indepth.dev/the-angular-ivy-guide-for-library-authors/) (have a look at the table with the different Angular versions), libraries built in Angular 9 are still compiled with the `View Engine` instead of `Ivy`, making them backwards compatible, so we shouldn't need a major new version.

That being said: I will gladly test this on older Angular versions to make sure it still works as expected. The documentation doesn't mention it, but up until what version do you aim to support this library?

**Comment by fetrarij** [comment]
Awesome, angular 8 should be fine.

**Comment by tsteuwer-accesso** [comment]
@Timebutt, can you address the conflict on `package-lock.json`?

Thanks!

**Comment by fetrarij** [comment]
@Timebutt @tsteuwer-accesso you can merge your branch from  origin master then remove package-lock.json and do a new npm install to have a fresh package-lock.json

**Comment by Timebutt** [comment]
@fetrarij fixed ✅

**Comment by fetrarij** [comment]
Thanks @Timebutt

**Comment by tsteuwer-accesso** [comment]
Thanks @Timebutt!

**Pull request merged**
