### PR TITLE
Update daterangepicker.component.ts

### PR DESCRIPTION
**Pull request by akashmehta-gep**

### CODE REVIEW

**Comment by akashmehta-gep** [comment]
@fetrarij  this will fix issue https://github.com/fetrarij/ngx-daterangepicker-material/issues/267

**Comment by fetrarij** [comment]
I am merging your PR since I wont work on v3 anymore. Thanks

**Comment by akashmehta-gep** [comment]
> You should select the startdate in left first then choose enddate in right. If you want to navigate in whole month in right dont select a startdate first.
> Best solution is to use linkeddatepicker so he right calendar will change with the left one

Even if you use linkeddatepicker then I can't select multiple months. Suppose, I want to select Jan to Sep. Then as soon as I select September in right date picker then left date picker changes to August

**Comment by fetrarij** [comment]
@akashmehta-gep so dont use linkeddaepicker but select the startdate in left first then navigate the righ calendar to september and choose the end date, that is the real behaviour.
With your PR, if we select on left calendar (eg: august) we can still navigate to july and june... so this is not the correct behaviour :)

**Pull request merged**
