### PR TITLE
 added sense of direction on custom range selection

### PR DESCRIPTION
**Pull request by batgos**
Allow to choose the end-date first in custom range
Swap start-date and end-date if end-date is lower than start-date

### CODE REVIEW

**Comment by fetrarij** [comment]
Hello @batgos , thanks for the PR.
You have only forgot to add `customRangeDirection` in the darerangepicker.directive.ts so I fixed it and merged your PR.
Thank you

**Comment by batgos** [comment]
Hello ! 
Thanks to you ! Sorry to have forgotten it  ^^
When will you do a release pls ? Cuz i need it asap

**Comment by fetrarij** [comment]
@batgos I ve released the v2.1.4, you can close the related issue. Thanks again

**Comment by batgos** [comment]
Thanks man ! It's help me a lot
But I have an error of "module not found" when i'm updating to 2.1.4 
2.1.3 is working well

**Comment by fetrarij** [comment]
A new version fixing this issue is now available. @batgos

**Comment by batgos** [comment]
Thanks @fetrarij  !

**Pull request merged**
