### PR TITLE
Show months arrows disabled

### PR DESCRIPTION
**Pull request by styopdev**
In our project we needed to show but disable months arrows even in the case navigation is not possible.
Would be a great addition to library.

### CODE REVIEW

**Comment by fetrarij** [comment]
Hello @styopdev , thanks for the PR.
What if you change `showDisabledMonthControl` to `alwaysShowMonthNavigation` or something like that?
And add it in the doc (readme).
After that, I will accept your PR ;)

**Comment by styopdev** [comment]
Hi @fetrarij, thank you for reply.
should `alwaysShowMonthNavigation` be a replacement for `showDisabledMonthControl`.  
If you want I can make additional property 
`alwaysShowMonthNavigation` - always shows controls despite of min/max dates
`showDisabledMonthControl` - always shows controls but it is disabled in the case if it is out of range.

Let me know your opinion and I am ready to change as you wish. The first one we don't need in our project but might be useful for someone else.

**Comment by fetrarij** [comment]
@styopdev I have tested.
With your implementation, even if the arrow are marked disabled (and may be the css made it invisiblle), the click to the arrow container still work, it makes the next and prev available event if it should not be.

**Comment by styopdev** [comment]
I'm sorry for that, I used a little bit tricky solution in pure css as I wanted to avoid js changes.
Could you please provide me the environment data you have tested on? 
OS and browser, thank you

**Comment by fetrarij** [comment]
@styopdev take a look and even you can try this https://thumbs.gfycat.com/SkeletalImpossibleBullmastiff-mobile.mp4

**Comment by styopdev** [comment]
Thank you, I will have a look, fix the problem and update PR.

**Pull request closed without merging**
