### PR TITLE
Added 'material' and 'showCancel' attributes in the component. To apply material theme colors.

### PR DESCRIPTION
**Pull request by yousefkhan**
showCancel:
By default the cancel button is not shown. You have to set this attribute to true if you want cancel button.

material:
To use the material theme if someone is using material design.
Setting this attribute to 'true' does the following.
1) Uses the mat-raised-button with primary color for 'apply'.
2) Uses the mat-flat-button with primary color for range buttons
3) Uses the mat-raised-button with accent color for 'cancel'
4) Uses the mat-icon with warn color for clearing the date.

### CODE REVIEW

**Comment by fetrarij** [comment]
hello @yousefkhan , thanks for the PR.
- showCancel is good, but you forgot to add this for the non material theme too
- material theme is good,  but the only problem is, the plugin will always depends on @angular/material even a project which wont use it.

any other solution?

**Comment by yousefkhan** [comment]
@fetrarij you are welcome

- Yeah I see that showCancel is missing for non material theme. Probably missed testing it on non-material.
- For material theme! yes you are right. In my case, I needed the component to behave like that as I was already using material dependency. So I made this change just in case it is useful for others too, But your point is totally valid that this will always require @angular/material even if someone does not need it. 
I am not sure yet how I should fix that. I will look into it.
Thanks for the quick feedback

**Comment by fetrarij** [comment]
Hello @yousefkhan .
Could you separate the PR in  two parts:
- first one for the showCancel functionality, so we can merge it to master.
- Then the second part  for the material theme ( Be sure to have the latest code from master after merging the showCancel, and I've added some feature such timepicker so you would change it to use mat-select too)

I'm planning to set a new branch for the material theme and a special tag for it like v2.0.0

**Comment by yousefkhan** [comment]
Sure. I will do that today

**Pull request closed without merging**
