### PR TITLE
Lock start date if needed

### PR DESCRIPTION
**Pull request by kgiann78**
Hi there! I love your job and I will try my best to contribute to this module.

We have came to the need to be able to lock the start date. This can happen for an activity that has already started and so the start date cannot be changed but only the end date.

So, a new flag (lockStartDate) has been and if this is true, for an existing date range you can modify only the end date.

I have also resolved many tslint errors and thus the many changes in different files...

Please let me know if there is anything more to add for this PR...

### CODE REVIEW

**Comment by fetrarij** [comment]
Hello @kgiann78 , thank you for PR I appreciate.
But I have just pushed the other PR to master and I want to merge yours too but now I have a conflict.
Could you fix this and add your change into the readme?

Thanks

**Comment by kgiann78** [comment]
I thought that I had already pushed everything several days ago... It seems I was wrong....
Please check the latest push to this pull request

**Comment by kgiann78** [comment]
The latest changes, customRangeDirection and lockStartDate, will look awkward if they are true together but I guess this is up to the developer...

**Comment by fetrarij** [comment]
@kgiann78 Thank you. I really appreciate

**Pull request merged**
